name: productdrivers
description: ProductDrivers analytics SDK for Flutter
version: 1.0.0
homepage: https://github.com/productdrivers/sdk-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.productdrivers.flutter
        pluginClass: ProductDriversPlugin
      ios:
        pluginClass: ProductDriversPlugin

